apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: access-control-secret-provider-class
spec:
  provider: vault
  secretObjects:
    - secretName: access-control-credentials
      type: Opaque
      data:
        - objectName: cache-manager-base-url
          key: CACHE_BASE_URL
        - objectName: cache-manager-client-id
          key: CACHE_CLIENT_ID
        - objectName: cache-manager-client-secret
          key: CACHE_CLIENT_SECRET
        - objectName: cache-manager-token-url
          key: CACHE_TOKEN_URL
        - objectName: cache-manager-scopes
          key: CACHE_SCOPES
        - objectName: plums-base-url
          key: PLUMS_BASE_URL
        - objectName: plums-client-id
          key: PLUMS_CLIENT_ID
        - objectName: plums-client-secret
          key: PLUMS_CLIENT_SECRET
        - objectName: plums-user-key
          key: PLUMS_USER_KEY
        - objectName: plums-issuer
          key: PLUMS_ISSUER
        - objectName: plums-audience
          key: PLUMS_AUDIENCE
        - objectName: plums-scopes
          key: PLUMS_SCOPES

  parameters:
    roleName: retail-hub-identity-access-policy-read
    vaultAddress: retail-hub-identity-access.vault
    objects: |
      - objectName: cache-manager-base-url
        secretPath: retail-hub-identity-access-kv/data/access-control-credentials
        secretKey: CACHE_BASE_URL
      - objectName: cache-manager-client-id
        secretPath: retail-hub-identity-access-kv/data/access-control-credentials
        secretKey: CACHE_CLIENT_ID
      - objectName: cache-manager-client-secret
        secretPath: retail-hub-identity-access-kv/data/access-control-credentials
        secretKey: CACHE_CLIENT_SECRET
      - objectName: cache-manager-token-url
        secretPath: retail-hub-identity-access-kv/data/access-control-credentials
        secretKey: CACHE_TOKEN_URL
      - objectName: cache-manager-scopes
        secretPath: retail-hub-identity-access-kv/data/access-control-credentials
        secretKey: CACHE_SCOPES
      - objectName: plums-base-url
        secretPath: retail-hub-identity-access-kv/data/access-control-credentials
        secretKey: PLUMS_BASE_URL
      - objectName: plums-client-id
        secretPath: retail-hub-identity-access-kv/data/access-control-credentials
        secretKey: PLUMS_CLIENT_ID
      - objectName: plums-client-secret
        secretPath: retail-hub-identity-access-kv/data/access-control-credentials
        secretKey: PLUMS_CLIENT_SECRET
      - objectName: plums-user-key
        secretPath: retail-hub-identity-access-kv/data/access-control-credentials
        secretKey: PLUMS_USER_KEY        
      - objectName: plums-issuer
        secretPath: retail-hub-identity-access-kv/data/access-control-credentials
        secretKey: PLUMS_ISSUER
      - objectName: plums-audience
        secretPath: retail-hub-identity-access-kv/data/access-control-credentials
        secretKey: PLUMS_AUDIENCE
      - objectName: plums-scopes
        secretPath: retail-hub-identity-access-kv/data/access-control-credentials
        secretKey: PLUMS_SCOPES
